### ISSUE TITLE
Фигурные скобки тут не обязательно, это для сложных выражений

### ISSUE THREAD

**Issue by bziondik** [Giltias/HomeWork#1]
https://github.com/Giltias/HomeWork/blob/b24d1f27f8d8f3f04f8797335519316b8991836c/hw1/test.php#L7-L8

echo "Меня зовут: $name" . PHP_EOL;
echo "Мне $age лет" . PHP_EOL;

**Comment by Giltias** [comment]
Это понятно, я так обычно и делаю, но сам сторм слегка лучше понимает и подсвечивает в скобках =) я думал вообще через sprintf сделать, но в задании такого нет

Последним коммитом убрал скобки
