### ISSUE TITLE
Попробуй без дополнительно массива :)

### ISSUE THREAD

**Issue by bziondik** [Giltias/HomeWork#2]
https://github.com/Giltias/HomeWork/blob/b24d1f27f8d8f3f04f8797335519316b8991836c/hw1/test.php#L115

**Comment by Giltias** [comment]
Сделал без доп. массива, но с доп. переменной. Остаются еще варианты собственной сортировки по ключам, ну или array_reverse 

https://github.com/Giltias/HomeWork/blob/860616a0178bd6b44a68f742e9ea8d1e94040d36/hw1/test.php#L115-L118
